### PR TITLE
Added suggested changes in the hardware_arduino layer 

### PR DESCRIPTION
**Pull request by Suryansh470**

### CODE REVIEW

**Comment by Mayankm96** [comment]
I have made tons of changes to your code. Most of them were issues with the naming of thrusters. Please read the Developer's Guide again because you declared variable names in caps which is not what is recommended there (CAPS only for `#define` or `const` type data). 

six-degrees-of-freedom-ship-motions

Right now I am trying to build the custom messages and use that for the pressure sensor. I seem to be facing some issue. Would look at it again tomorrow.

**Comment by Suryansh470** [comment]
@Mayankm96 [Pressure](http://docs.ros.org/hydro/api/underwater_sensor_msgs/html/msg/Pressure.html) why aren't we using this ???? instead of making custom message?

**Comment by Mayankm96** [comment]
That is because the pressure sensor provides depth data directly and I want to use that instead of pressure, hence using the message named `Pressure` would cause confusion in future.

**Comment by Mayankm96** [comment]
This issue has been reported [here](https://github.com/ros-drivers/rosserial/issues/239).

**Comment by Mayankm96** [comment]
I am using the pressure sensor data only for now. We'll need to see about using the `Depth` message. I am merging the PR for now. Please review the changes I have made for your own benefit.

**Comment by Mayankm96** [comment]
I forgot to see the `control_layer`. Next time please send only __ONE__ package at a time. Or mention which all packages are there in your PR so that they can be reviewed accordingly.

**Pull request merged**
